query my_businesses($user_id: String!) {
  my_businesses(__id: $user_id) {
    businesses {
      __id
      business_name
      address
      city
      state
      latitude
      longitude
      header_image
      reviewCount
      ratingAvg
      business_category {
        id
        category
      }
      reviews {
        created_at
        rating
        review
        voteCount
      }
    }
  }
}
